"""Phase 2 mission state definitions."""

from enum import Enum


class MissionState(Enum):
    PREFLIGHT = "PREFLIGHT"
    MOTHERSHIP_TRANSIT = "MOTHERSHIP_TRANSIT"
    LOITER = "LOITER"
    DEPLOY_QUAD = "DEPLOY_QUAD"
    QUAD_INSPECT = "QUAD_INSPECT"
    QUAD_RETURN = "QUAD_RETURN"
    DOCKING_ASSUMED = "DOCKING_ASSUMED"
    CHARGING = "CHARGING"
    REDEPLOY_OR_RETURN = "REDEPLOY_OR_RETURN"
    RETURN_HOME = "RETURN_HOME"
    COMPLETE = "COMPLETE"
    ABORT = "ABORT"
